apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea
  namespace: abcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
      - name: servicea
        image: servicea:v1.0
        ports:
        - containerPort: 8080
        env:
          - name: DT_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: dynatrace-secret
                key: DT_API_TOKEN
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "https://bmm59542.dev.dynatracelabs.com/api/v2/otlp"
          - name: OTEL_EXPORTER_OTLP_HEADERS
            value: "Authorization=Api-Token $(DT_API_TOKEN)"
---
apiVersion: v1
kind: Service
metadata:
  name: servicea
  namespace: abcd
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: servicea
