apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicec
  namespace: abcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicec
  template:
    metadata:
      labels:
        app: servicec
    spec:
      containers:
      - name: servicec
        image: servicec:v1.0
        ports:
        - containerPort: 8082
        env:
          - name: DT_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: dynatrace-secret
                key: DT_API_TOKEN
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "https://bmm59542.dev.dynatracelabs.com/api/v2/otlp"
          - name: OTEL_EXPORTER_OTLP_HEADERS
            value: "Authorization=Api-Token $(DT_API_TOKEN)"
---
apiVersion: v1
kind: Service
metadata:
  name: servicec
  namespace: abcd
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: servicec
